services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev 
    container_name: nestjs_api_dev
    command: npm run start:dev    
    volumes:
      - ./:/usr/src/app           
      - /usr/src/app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"  
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: postgres_local
    environment:
      POSTGRES_DB: nestdb
      POSTGRES_USER: nestuser
      POSTGRES_PASSWORD: nestpassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  pgdata:

