services:
  api:
    build: .
    container_name: nestjs_api
    ports:
      - '3000:3000'
    env_file: .env # guarda aquí tus credenciales
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: postgres_local
    environment:
      POSTGRES_DB: nestdb
      POSTGRES_USER: nestuser
      POSTGRES_PASSWORD: nestpassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: unless-stopped # reinicia si se cae

volumes:
  pgdata:
